// The corpus: every snapshot banked in tmp/corpus/ (tmp/ is gitignored —
// deblob's own is regenerated by vitest.global-setup.ts, private ones dropped
// there by hand), through the App via a static source. Invariants of any
// snapshot: it mounts, every service root appears, the counts shown match its
// stats. Vite's glob import reads the directory: no `node:fs` in the viewer.

import { mount, unmount } from "svelte"
import { expect, test } from "vitest"

import App from "./App.svelte"
import { createStaticSource } from "./lib/snapshot/adapters/static-source.adapter.ts"
import type { Snapshot } from "./lib/snapshot/snapshot.model.ts"

const corpus = import.meta.glob<Snapshot>("../tmp/corpus/*.json", {
  eager: true,
  import: "default",
})

const statOf = (target: Element, stat: string) =>
  target.querySelector(`dd[data-stat="${stat}"]`)?.textContent?.trim()

test.each(Object.entries(corpus))(
  "%s: mounts, every service listed, counts match stats",
  (_path, snapshot) => {
    const target = document.createElement("div")
    const app = mount(App, {
      target,
      props: { source: createStaticSource(snapshot) },
    })

    const listed = [...target.querySelectorAll("h2 code")].map(
      (el) => el.textContent,
    )
    const roots = new Set(
      snapshot.modules.flatMap((m) =>
        m.serviceRoot === null ? [] : [m.serviceRoot],
      ),
    )
    expect(new Set(listed)).toEqual(roots)
    expect(target.querySelectorAll("li").length).toBe(snapshot.modules.length)

    expect(statOf(target, "files")).toBe(String(snapshot.stats.files))
    expect(statOf(target, "bytes")).toBe(String(snapshot.stats.bytes))
    expect(statOf(target, "blobPercent")).toBe(
      String(snapshot.stats.blobPercent),
    )
    expect(statOf(target, "services")).toBe(String(snapshot.stats.services))

    unmount(app)
  },
)
